### ISSUE TITLE
modificar un archivo

### ISSUE THREAD

**Issue by nbustos21** [CAMPUSCAMARAFP2021/prueba-uno#21]

**Comment by abeja21** [comment]
@nbustos21 que archivo haber si especificamos -_-

**Comment by nbustos21** [comment]
el que tu quieras guapetón

**Comment by abeja21** [comment]
EL ERCHIVO tres.json a sido modificado

**Comment by nbustos21** [comment]
vale caballero, gracias por tu comprensión y trabajo
