### ISSUE TITLE
Información insuficiente en el Readme

### ISSUE THREAD

**Issue by davidpestana** [CAMPUSCAMARAFP2021/prueba-uno#4]
El Readme del repositorio no dispone de información suficiente para entender como usar este repositorio.

**Comment by Salva-Blanquer-Bru** [comment]
lo resolvere enseguida

**Comment by davidpestana** [comment]
@Salva-Blanquer-Bru he incluido el commit, te parece correcto?

**Comment by Salva-Blanquer-Bru** [comment]
me parece correcto, sigue asi 👍🏽
